feat:created a basic api docker container
TrailExplorer/backend pull request #2
Opened 2024-03-14 23:03 UTC by Anirudhpk2001

2024-03-15 05:05 UTC, KaranBantia approved these changes
LGTM

2024-03-16 18:33 UTC, KaranBantia requested changes

2024-03-16 18:33 UTC, KaranBantia commented on requirements.txt
> +flask=2.1.0
should be ==

2024-03-16 18:46 UTC, KaranBantia requested changes

2024-03-16 18:46 UTC, KaranBantia commented on DOCKER
> +# Use the official Python image as a base
change file name to Dockerfile

2024-03-16 21:03 UTC, Anirudhpk2001 commented
Fixed!!! Can you Review now.

2024-03-16 21:11 UTC, Anirudhpk2001 commented on requirements.txt
> +flask=2.1.0
Done

2024-03-17 23:54 UTC, KaranBantia approved these changes

2024-03-26 04:22 UTC, sachi097 requested changes
Document the api - documentation must include how to access the api (parameters) and a sample response.

2024-04-04 21:06 UTC, merged